### ISSUE TITLE
when parsing MIME with a root TNEF part, binary content-transfer-encoding includes trailing \r\n

### ISSUE THREAD

**Issue by ghelyar** [jstedfast/MimeKit#484] opened 2019-05-23 15:20 UTC
**Describe the bug**
When a mime part is `Content-Transfer-Encoding: binary`, `DecodeTo` includes the trailing `\r\n` in the decoded stream.

This seems to commonly occur when the root MIME part is application/ms-tnef, although I don't know if there are other situations where binary content transfer encoding is used that also cause this to occur.

**To Reproduce**
1. Parse a MIME document where the root part is TNEF and the content-transfer-encoding is binary
2. Decode the TnefPart.Content
3. Look at the last 2 bytes of the decoded data

**Expected behavior**
Last 2 bytes should be the checksum of the final TNEF attribute

**Actual behavior**
Last 2 bytes are `0x0d0a`

**Other notes**
I don't have a sample message to attach because the messages I have seen this on are from real emails that I can't publish, but it's just MIME with a root TNEF part using binary encoding as described above where the final 2 bytes of the MIME are 0x0d0a

I'm not 100% sure if this is a bug with the binary decoding in MimeKit or garbage in garbage out in that the \r\n shouldn't be in the MIME stream in the first place. The MIME was captured in-flight with BDAT being used in the SMTP, so it should not include any extraneous bytes.

**Comment by jstedfast** [comment] 2019-05-23 15:45
You could add a hack in your code to call SetLength() on the content stream to trim out the trailing CRLF before parsing the TNEF data:

    tnef.Content.Stream.SetLength (tnef.Content.Stream.Length - 2);

As far as whether this is a MimeKit bug or not, as far as I know, this is one of those scenarios that is not well-defined.

When using BDAT, there's no need for the sending agent to terminate the message with a CRLF like there is for the DATA command (since DATA must end with `\r\n.\r\n`), so why is the extra CRLF being added?

I can't find any authoritative documentation on how to treat this, so I'm going to close this for now as "not a bug", but if you or anyone else finds any authoritative documentation on how to deal with this that says I'm wrong, I'll figure out a way to fix it. I just don't want to "fix" it only to create another bug where legit data is lost from the tail of the message.

**Closed by jstedfast** 2019-05-23 15:45 UTC

**Comment by ghelyar** [comment] 2019-05-23 17:41
Thanks for the quick response.

I couldn't find any clear documentation on this either.

If it isn't clear either way it's better to have too much than not enough. I can always ignore these bytes, I just didn't want to strip them when writing back to the `TnefPart` if they weren't supposed to be part of the content.
