### ISSUE TITLE
Gmail seems to don't like mixed encodings in recipient/sender name

### ISSUE THREAD

**Issue by Virus-X** [jstedfast/MimeKit#258] opened 2016-07-05 16:12 UTC
Hi there!
First of all, thanks for a great library. You rock!

I've noticed a strange issue with gmail. It doesn't show a part of sender name when it's mixed languages, e.g cyrillic + latin.
Here's example:
"Юра из Acme.com" gets encoded to: 
```
=?utf-8?b?0K7RgNCwINC40Lc=?= "Acme.com" <acme@light-spark.cloudns.org>
``` 
and shown in gmail as:
![bad encoding](https://monosnap.com/file/lJt4afvgjy5ix3CwDkgjgueXLVgbe6.png)

But when I add some cyrillic text to the end of name, it gets encoded in full and displayed correctly:
"Юра из Acme дот ком" -> 
```
=?utf-8?b?0K7RgNCwINC40LcgQWNtZSDQtNC+0YIg0LrQvtC8?= <acme@light-spark.cloudns.org>
```
![good encoding](https://monosnap.com/file/Od77qgUyUXUNboPebMkOzYxma8sBfo.png)

What are your thoughts about this? Maybe some option could be added to force full name to be encoded with QP?

**Comment by jstedfast** [comment] 2016-07-05 22:02
GMail should really be fixed to handle this :(

**Comment by Virus-X** [comment] 2016-07-06 09:30
Posted a question to Gmail team: https://productforums.google.com/forum/?hl=en#!topic/gmail/A3wuMROHxVc;context-place=forum/gmail

Hope that they'll fix it, but I think it could take a while. Unfortunately, I need to fix this behavior in my product asap, so I'm planning to make a fork of MimeKit and tune it. Perhaps, it's good idea to extend AllowMixedHeaderCharsets=false behavior, so it wold ensure not only same charset for all encoded parts, but also that all parts are encoded if one of them need to. 
Or, alternatively, add a new option to FormatOptions. Haven't decided yet.

Do you think such option may be helpful and included in main repository? If yes, I could make a pull request.

**Comment by Virus-X** [comment] 2016-07-06 14:46
Hmm, strange thing. I've added an option to Format options, and was trying to pass it to the MimeMessage object, expecting that headers would be serialized using specified options:
```
 message.WriteTo(new FormatOptions
                    {
                        ForceFullHeaderEncoding = true
                    }, stream);
```
But it turns out that headers are always serialized with FormatOptions.Default at the point I add them :(

**Comment by jstedfast** [comment] 2016-07-06 20:16
https://github.com/jstedfast/MimeKit/commit/cb33c4a39396439a9786600ff98d72fe36bf7314 fixes that

**Comment by jstedfast** [comment] 2016-07-06 20:45
I don't think I'll accept a patch to work around this gmail bug so closing.

**Closed by jstedfast** 2016-07-06 20:45 UTC

**Comment by blong42** [comment] 2016-08-16 23:43
Thanks for the bug report, there is indeed a bug in Gmail's parsing of this address.

This isn't related to the mixed encodings, however, the issue is actually with multiple quoted strings.  Our first pass undoes the rfc2047 encoding, which results in a quoted-string, and then we drop everything after that.

Ie, the following is equally broken:
"Foo" bar <foo@bar.com>

The fix should be in production in a couple weeks.

**Comment by jstedfast** [comment] 2016-08-17 00:25
Thanks @blong42 for looking into this issue on GMail's side!
