### ISSUE TITLE
Mail parse error : "Error Failed to parse data." 

### ISSUE THREAD

**Issue by madagaga** [jstedfast/MimeKit#448] opened 2018-11-22 09:38 UTC
Some mails can't be parsed when retrieved from server with MailKit.
The first line of raw email seems to be encoded in base64. 

example : 
AdMgkmhqf2IeNew7j+gA8L5jAnlGoCpH/edixmG0QjnMS5mTPVP/cGlZ9TUreAkjTy36TX8EqGtvfhfuehVhk96HBbGiMYMiFnJMncBHamLyKuLtGEU5LdplU8pmxbez2xRu+OK4nhEq4rnYnoD5RCk2E4j67+XVTd6uw=
Resent-From: <xxx@xxx.xx>
Received: from xx.xx.xx.xx.com
 (2603:10a6:800:4a::21) by xxx.xx.xx.xxx.com
 (2603:10a6:10:20::24) with xxx SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.1294.27; Tue, 20 Nov
 2018 05:30:04 +0000

Fails here : 
https://github.com/jstedfast/MimeKit/blob/master/MimeKit/MimeParser.cs#L1565

**Comment by madagaga** [comment] 2018-11-22 09:45
This can be a email format problem. But mail can be opened with mail client.

**Comment by jstedfast** [comment] 2018-11-22 12:07
Yea, the problem is all of the gobbeldy-gook at the lead of the input.

I'm going to close this because MimeParser is meant to parse reasonably-well-formed message content, not handle random garbage.

**Closed by jstedfast** 2018-11-22 12:07 UTC
Labels: invalid
