### ISSUE TITLE
DKIM validation fails for gmail messages

### ISSUE THREAD

**Issue by rbfajardo** [jstedfast/MimeKit#288] opened 2017-03-13 23:23 UTC
I've created a public key locator class that fetches the public key/dns for a message with a DKIM signature. I then call into MimeKit message.Verify() but this comes back as false when validating a signature from gmail. Any other message from another external source works just fine. Am I doing something wrong or is there a bug in MimeKit? This works as a transport agent in Microsoft Exchange.

```csharp
// code from my public key locator
try
{
   byte[] pubKeyBytes = Convert.FromBase64String(dict["p"]);
   this.foundPublicKey = true;
   AsymmetricKeyParameter key = PublicKeyFactory.CreateKey(pubKeyBytes);
   this.validPublicKey = true;
   return key;
}

// code from my agent
// Loop through all header and find the first DKIM signature
if (messageHeader.Id == HeaderId.DkimSignature)
{
   foundDkimSignatureHeader = true;
}

verifyResult = message.Verify(messageHeader, keyLocator);
```

**Comment by jstedfast** [comment] 2017-03-13 23:29
Do you have a sample message? The ones I have verify correctly from GMail.

**Comment by rbfajardo** [comment] 2017-03-14 00:09
[raw_message_sample.txt](https://github.com/jstedfast/MimeKit/files/839929/raw_message_sample.txt)

File attached

**Comment by jstedfast** [comment] 2017-03-14 01:05
It seems to fail with the body hash but I've checked and MimeKit hashes the exact same bytes as the raw message, so it's not a bug in MimeKit.

Here are the rules for relaxed body canonicalization:

```
3.4.4.  The "relaxed" Body Canonicalization Algorithm

   The "relaxed" body canonicalization algorithm MUST apply the
   following steps (a) and (b) in order:

   a.  Reduce whitespace:

       *  Ignore all whitespace at the end of lines.  Implementations
          MUST NOT remove the CRLF at the end of the line.



Crocker, et al.              Standards Track                   [Page 16]

RFC 6376                     DKIM Signatures              September 2011


       *  Reduce all sequences of WSP within a line to a single SP
          character.

   b.  Ignore all empty lines at the end of the message body.  "Empty
       line" is defined in Section 3.4.3.  If the body is non-empty but
       does not end with a CRLF, a CRLF is added.  (For email, this is
       only possible when using extensions to SMTP or non-SMTP transport
       mechanisms.)
```

Given that, the canonicalized body text would look like this (i.e. no change from the original data):

```
--94eb2c07027e132231054aa588c9
Content-Type: text/plain; charset="UTF-8"

Test Message body

--94eb2c07027e132231054aa588c9
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8">Te=
st Message body&nbsp;

--94eb2c07027e132231054aa588c9--
```

**Comment by jstedfast** [comment] 2017-03-14 01:08
Are you sure that this message is supposed to verify?

**Comment by rbfajardo** [comment] 2017-03-14 01:14
Thanks this helps, exchange could be doing something to the body. I'll debug this further and comment here what I find. Thanks again!

**Comment by jstedfast** [comment] 2017-03-14 01:16
Let me know what you find out. I guess I can close this for now.

**Closed by jstedfast** 2017-03-14 01:16 UTC

**Comment by rbfajardo** [comment] 2017-03-14 03:26
You help was key, thanks. Captured the raw data over the wire, looks like exchange is changing the body by adding the <meta> tag. I will dig into this some more and comment again when I figure it out.

**Original:**
--f4030435bc241ad9c7054aa7c36f
Content-Type: text/plain; charset=UTF-8

Test Message body

--f4030435bc241ad9c7054aa7c36f
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Test Message body=C2=A0

--f4030435bc241ad9c7054aa7c36f--

**How it appears in the mailbox:**

--f4030435bc241ad9c7054aa7c36f
Content-Type: text/plain; charset="UTF-8"

Test Message body

--f4030435bc241ad9c7054aa7c36f
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8">Te=
st Message body&nbsp;

--f4030435bc241ad9c7054aa7c36f--

**Comment by rbfajardo** [comment] 2017-03-14 04:52
Ignore what I said earlier regarding the meta tag. Looks like this tag is added after the message is injected into the mailbox well after DKIM verification. I found the problem... Exchange is adding quotation marks in the "Content-Type" header around "UTF-8". As seen in the example above, Gmail does not include quotation marks during send but Exchange adds them before it gets to MimeKit. I'm guessing it is added while the message is parsed maybe to comply with some RFC.

I was able to test this by simply converting the stream to text/string and changing the header back by removing/replacing the quotations. @jstedfast - Is this something that can be handled in MimeKit?

`Stream stream = mailItem.GetMimeReadStream();
StreamReader reader = new StreamReader(stream);

string rawEml = reader.ReadToEnd();
rawEml = rawEml.Replace("charset=\"UTF-8\"", "charset=UTF-8");
byte[] rawEmlBytes = System.Text.Encoding.ASCII.GetBytes(rawEml);

MemoryStream memoryStream = new MemoryStream(rawEmlBytes);
MimeMessage message = MimeMessage.Load(memoryStream, true);
verifyResult = message.Verify(messageHeader, keyLocator);`

**Comment by jstedfast** [comment] 2017-03-14 11:52
Not really because MimeKit can't know what changed. Not all clients will remove the quotes, some clients might remove some quotes and not others, the list goes on and you end up with an impossible number of combinations of things to munge.

**Comment by rbfajardo** [comment] 2017-03-14 12:58
Thanks again, I will figure out a way to handle this scenario going forward.

**Comment by brunocz6** [comment] 2021-12-16 17:22
> Thanks again, I will figure out a way to handle this scenario going forward.

@rbfajardo Hello, i know this is such a long shot, but did you manage to solve the issue? I also have exactly the same issue, where our company exchange server wraps the utf-8 in quotes...

Thank you kindly for your response

**Comment by rbfajardo** [comment] 2021-12-16 18:08
Yea sort of ... what I am doing is getting the raw message, but I am not sure if my approach is the best considering there could be different encoding types. Once you get the raw message, you can use mimekit to validate the signature.

Code below uses an old version of mimekit by the way.

```
        public bool VerifyMessage(MailItem mailItem, out bool dkimSignatureHeaderFound)
        {
            bool result = false;
            dkimSignatureHeaderFound = false;
            MimeMessage message = MimeMessage.Load(GetRawMessage(mailItem));
```

```
        private static Stream GetRawMessage(MailItem mailItem)
        {
            StringBuilder builder = new StringBuilder();

            using (MemoryStream stream = new MemoryStream())
            {
                Microsoft.Exchange.Data.Mime.EncodingOptions options = new Microsoft.Exchange.Data.Mime.EncodingOptions("US-ASCII", "en-US", Microsoft.Exchange.Data.Mime.EncodingFlags.None);

                // Get the raw message headers and convert to string
                mailItem.Message.RootPart.Headers.WriteTo(stream, options);
                string messageHeaders = StreamToString(stream);
                builder.Append(messageHeaders);
                builder.AppendLine("");
            }

            // Get the message body and convert to string
            string messageBody = StreamToString(mailItem.Message.MimeDocument.RootPart.GetRawContentReadStream());
            builder.Append(messageBody);

            return StringToStream(builder.ToString());
        }
```
