### ISSUE TITLE
Failed to parse message headers. issue

### ISSUE THREAD

**Issue by angleafro** [jstedfast/MimeKit#151] opened 2015-07-15 10:53 UTC
I think this error is same kind of #77 (MimeKit: MimeParser and incorrect message headers #77 ).

When debuging MimeKit source code following line throw error.

" if (Step(inbuf) == MimeParserState.Error)
 throw new FormatException("Failed to parse entity headers.");"

If you request a eml then I will send to you.

Thank you for reading.

**Comment by jstedfast** [comment] 2015-07-15 11:24
Yea, if you could send me a sample message that causes this, that would be great. Thanks!

**Comment by angleafro** [comment] 2015-07-15 13:00
Sooy, It is my mistake.

Error messge is differnet . following line thow exception(imePsrser.cs 1424 line).
while (state < MimeParserState.Content) 
{
if (Step (inbuf) == MimeParserState.Error)
throw new FormatException ("Failed to parse message headers.");
}
and I Sent an mail to you.

Thank you.

**Comment by jstedfast** [comment] 2015-07-15 13:12
I have not received the email (I've checked in my Spam folder as well). Did you send it to jeff@xamarin.com?

**Comment by angleafro** [comment] 2015-07-16 01:38
Sorry for late.

I Sent an email that can't send to you (jeff@xamarin.com )

I check now retry sand to you.

thansks.

**Comment by jstedfast** [comment] 2015-07-16 01:59
The problem is that these are not headers:

```
MAIL FROM:<x@x.com> SIZE=28451 BODY=8BITMIME
RCPT TO:<x@x.com>
DATA
```

MimeKit is not an SMTP command interpreter.

**Closed by jstedfast** 2015-07-16 01:59 UTC
