### ISSUE TITLE
Cannot verify signature with imported cert(s), Failed to verify digital signature: non-empty set required

### ISSUE THREAD

**Issue by Vandersteen** [jstedfast/MimeKit#558] opened 2020-04-18 01:35 UTC
**Describe the bug**
When using the TemporarySecureMimeContext, I always get `Unhandled Exception: MimeKit.Cryptography.DigitalSignatureVerifyException: Failed to verify digital signature: non-empty set required`. However, I can verify these signatures with other tools (openssl, ...)

**Platform (please complete the following information):**
 - OS: [Linux, MacOS]
 - .NET Runtime: [CoreCLR, Mono]
 - .NET Framework: [.Net Core 2.2]
 - MimeKit Version:  2.6.0

**To Reproduce**

Sign a message with any key (I tried multiple different keys), importing fullchain certs, self signed certs.
To no avail.
I am using Mac to develop, and run it on linux (Docker). On both platform, the same error happens.

```
    var pem = "path/to/fullchain.pem";
    using (var ctx = new TemporarySecureMimeContext())
    {
        using (var s = File.OpenRead(pem))
        {
            var parser = new X509CertificateParser();
            var certs = parser.ReadCertificates(s);
            foreach (X509Certificate cert in certs)
            {
                ctx.Import(cert);
            }
            foreach (var signature in await multipartSigned.VerifyAsync (ctx)) {
                try
                {
                    bool valid = signature.Verify(); <--- boom
                } catch (DigitalSignatureVerifyException e) {
                    // There was an error verifying the signature.
                    throw e;
                }
            }
        }
    }
```

**Expected behavior**
It verifies the signature using the cert chain imported in the context

**Comment by Vandersteen** [comment] 2020-04-18 02:09
For your convenience, includes:
* Creating a multipart signed
* .pfx for signing
* .pem cert for verifying

```

var keyStream = new MemoryStream();
await keyStream.WriteAsync(Convert.FromBase64String(
    "MIIQCQIBAzCCD88GCSqGSIb3DQEHAaCCD8AEgg+8MIIPuDCCBe8GCSqGSIb3DQEHBqCCBeAwggXcAgEAMIIF1QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIGrNu16CtHGoCAggAgIIFqEPIdFZ73Lc6EyoP/OVHrdWkwH5+Uctu39UNHF0F2fGdiwk/ThN/0IYZPcfIkwLoaHPYjCe+CsJQUOplTz/aeecRxnyout2eu88eareGKLx6ppMUvGP7nNW0htRvOJLCMmBkSeO6deywGvrTbdNVdS8BCeNZN4jBYbm3PUacI34/M/uBTvaMFTYvPw5gXMObOpQ1NQoVwwg79o22aGi72FxYZsxErtFcCfH/r1rDJz54C0f5IOelvfFZ4KNqFlF+ASnosprWJpVJUmpJCh5A5z1b6E1m/ZQwK6hIBDGBtpI/q487SSEMwiktTULCnFcQUa0b7J3U6SCs14sw4D0TsA0u4PvugmRyPc89Sp9TH+O1adrHs0Pa2a6ABjrcszPtS1pkKSaOPzq16pfyeMC87rRtGszsbtv5dL7HAQLfBdHvRS8cVLLN16DNOQsDKINvBLfzw6DWl43NfiF44oyGIQkKRvXCR1JA2plU6/YwwEvNjZBDRpYxay/VEoIulilHb3CaXdHFJKmENNdmv/Qd53CX5dRynSUkvLustNr60VJ5jJqwxP4Mkm3uhl8eKdqijetOojX790bBdMqbSyTbpNnlLYCJDWvu4FSxdqVbXJ0AqQT7jWmSV4hSq6dFZdSaeT4hX4+Uto3q2fxZXxBz5BPi4/L1L635dg0VHQJ2F37TqVI1WTcJ4K+ch62uggiyaU2z/J/NBoguQh2Y8BoeJ6NaZvCms1lAVbMJAGTntqafA+iYqceVP8f+qBgOAFjtm+1PwNYCNOWyK5M81X4Eci+W/SSgFTEI0Uly2G8a+bGQJXwDPdPG+jABwrzzusV9fOS41BEl2QQAe96ke9dnmk1HNpR1g4I/LnuiW1VW4BBzOU+1i7jjj185KSdDRCJdQjpubzKwh99RNytck/mzWrv1j8buG2PmEAwtifakHdrdp1BVRKIiuEXEFm8k5qWIAn5t85rflkw7yjaFK/twCMl8+GBLGuoDx7b40fUWZql+bPMqXaFj+e2kqi6AqwF2XWjQagyc65ckchg5TxqhsnwG9faZNfQ8i0RjNGUx3sNkEnPBrAmRMrRzs9QfipjIspTePpFv1GlgB2B7N7JubNoBN4GQd+3PelWZl8HErhtQ/fdBBlwLaaBiDqxm8owKCpZuh+sRUauyTCVXrCZBLEL77aTz8aXZ6yJG6MB/54KVHOWOvGYbxTI2UX99eiqUh7xdzIKBm2sFmc52cDrA+LVh28+qiCAiE0N8+Ls0dIdpH1FTYP0oX5LHN19SSnyUc6/auNHkIRlzCl6nXSWf1w6YU2vq5rhWvr04UtF3mlZwEAdGgEIRCmDKc5gKzLKiixsT5cYiPBx8dwtGmyM0SN6q6jAWNSp2tcxYzkgcjSEB0mEWKp376ZEq7AxJF6Lag88kaWtBLUZb23vUxkm0SX+eTiiczS1+Zl8pCxHhbGuwHjCwWCsCpUxcllFwbnmid9bVxkPHqU+O7feypWZpygkHYsA4scy2DHnJGoGYI+csRJT+9jV4/DzJJ1e0S6nyjRMszuKRjrb4vd52JU4BP0FuzW/ImKOeFYuCGT1x/2gLtFN3LeJygx7ls/rcuMQvYCrg/UfWVPnp6ioBCnXBtLOfiRhwn4WoDp3XH13LRz5gCHwJSa3BU4xZWo/EwnSqiZUP06nhpZ7Uoqitk6sYUlSIVxSzORjjZtP8mXmrjMUvjny8Jq7AyI3ndiN3UhUM55GbanEzspMnzaiUKOlpijvPajI+NKmsO+sWYCkaNjMd4JY98I2Ww4Kxel75JUnIxSOIAcSPv7Q3EdNo0j5G9DMS9VTkXfAuAyJqz60FTYMq7hLVM4MAvuP6SBJBOOsCgmVd8cAslKzsdBKbuQ3BrvEldwuuUH6lOxULKQGwTnX+7nSW5cfUNHfEQSL3wJhWGUG49qeH5yt8MIIJwQYJKoZIhvcNAQcBoIIJsgSCCa4wggmqMIIJpgYLKoZIhvcNAQwKAQKgggluMIIJajAcBgoqhkiG9w0BDAEDMA4ECMRpKKOUDcpfAgIIAASCCUh2+hVuKB4WxAymZ7SDLHLB6wijpT/sR4XAUhuhIMYnlfp0XAHouOhkHPaWwjebhxQXkfSseJv5KCwps8XvGzZpZ30RRzArn8iamf4Px7hnN2VODVpTatGUydTq6SjIkmlUT4eFv5zMBIUy/P/XW5CknrPEBpLBpAUQeRgDgRu8Ra2FLnFaQvsELS9TZ0mm56R+r0MYoTPaX70H3hDq/9T9QYNTkYGYFLQ4fieucr/mqshA1ZxHSzZYxPlaRGINrZ5eK3p4gYoZ4IqdSYnxTJgdRnQcYn6zFW77VTIjiPgT9f27HuW6/hFW49AJmL3r2wr+HJvnANS6r4M0NP+6fzJq8cSDNTix/UP/TDDmw3ZnkNCPiXlrw2OqebQJPPW/LNMd+Jzqrct/o6282ZTOl8mrOfrG2yxf5C6+p4vj2lig+zGGA0cl9cl4D8Rve8Si/2syaoE1OinCB3PW7KzA1Nihb5mbwaU4GnCUwHmphnqxxQhco9rCTc59hPayQsGmv+FlA11b26m/vOd0oah8EMM5P7o679I1UJNfxx6ruJ/idrt6A2LpnVVPnCvUr8SN4oqsfsZRbKWoX8dY4miCKr6BVyGVDznhuAQfkYGrAmR8o1nvqZ7aAxjHy4ZZcbqTnTZ0buKOCOy6RUd3v4OqTFAtEFKb8oNRgzkEbE+KyobZalRrxYeeb9ZIGwu87n3PCOhoo/z3wWQLiWLvEzd2xmlYz9queDDM4cDsZNvR5kJDGRpHtmS5kKxAgQuH8ljJ8mMUVEQNwqAsedITd4EHoWvYGx+A1igzzfO6wyaveh40uHgBIPYxgAGKduxeBKj0N4ZM+vdoCOYvMUJvClfpvxkm9hZLbI5opUePwZzNm2io/Bb4IjMZjlO5pt1ZcC1Joou6T0k/HPFgyNUSXJtuWkb65W7VAOO6690C2xnhNAJX03m22g3zdCAp1XSPj8XknA5R3jTKK/InFy22Lwh7S7aeAiDCMaijwE99D+KBK6lTnAqsMzFwf7Nkm4DvDcIsucjVsBvD5EgASDItD3vnHsduSXKZks7sOv94mONKKG0RyhN2261p2VEj8GHRWIg0+B0CJ/bZKqSUxNWCyAMBJ2ATZWwYL3JBFytz9tZgeDyJwTtghVQV83bRpOex4pJoIyxAQBNvot+a7J6ML+ZLQXvjlGXDhfyLu9wVFyHsyxwGK5PgCb0T29bgy10uuiY5dr05RwSbiTHZ7C3O6JxxifYmlKagpplU0oIL2r5MmMl6oQthH3CZCPB0fAwC5a8INSX2Jgl/BmXbVAB35BUGFTkaZUKRX/Jl62k+yy1pQPlnkdiIXnQu8ddfkxHNXilKMkmQm7JnJXpMq/my//WXvTWYBeD2I4IbJVKvQ35vUobLRK8ixDxNGt5lnJUfYA0ctcUi1ilcxXhsYiYfHiMuaNcAGl9jb4FxLpd1wGWSF8MbxNTNWTlTjw4Z+nWbejRtxKZ0cH0uiiayZu0AfjwUhc/+iL17aWNRjLm7JbeMpS750mP6/zizXwI3+QqBYP8cNtjuLYl8uiUn5/xGZHvpe9AHCZQ68zPPK5gJWG8LzwsETm6QpxZnAA+RdafSTrCsIWa4POAUjsgOcCQ9mUPNsuhtN763mdedTxyYizKoWylGCwxw8ABJQb3OPC6RZzDqxGWYy+6/jKACHuOWeqrP6sprMTqTMoQ3WHzIemSXUetUpENdvW00dqejdzA1vs93KAhtHDgYfj8ziEh0YYSXj/eXT+ob2Aj5U33Sc5FPjSPxf6TF92Tyieq6M/UW+bXiO9bl9Yr1Hmj7/Bygd2cMkUD+PC4UkJ2fvE7BnmINMvuXfEWeuFxnsAcZLFBTGZUXxmc3dAE0qVQeYbeE8hpU8dzflUR5YgtXrbbFc67QFcYGxj7tvLE/WUXfj1vTACUOlPQXhDnBbAQi+NwSxE0ZksaPD+EJ7jHv6FhrYgPT0TLuExgdRuqrr84Upq6bMG0INos/EioDl7piFCFr9STJHh+0e0ul2chsWP3bxqLb7PglAFlbi0Qu3feN+DA7/srj8lq/bpeosPnTa6SUKjUeyiL3V9jMnncpqQpgXaUAPAIKeNjXVLNbntNr1ZcXXvPfg4O3sw5ruhuHxBLfttSWyKlJVxaftm28qwTK44lseXO2koJ++L328yVWPc9YSu58Q9Lq9NZwFGc05Yrq72SJA1FNC4nE2hR6JTsPWcWtUge+LEoIc5GyACEoc+FrAnQvdYn9XQn1tU3yqDCq7ENnIbwfw4s/f3mzsb1XV3Mk0E/Jkh+4/30K7pXJ6zTZ3hec7t1rxkx+nvmsBWuswxnxk6+LMfVvCcwv0cWaUDqXlNLf2sOlDkdwZ/PiSLJiom0ox50dXoqZs1a07XTWRy9v+xKm/HDjDQkChEPwch7AF9vIShQzqtmDzX366K/oYrmo3x/iRKfQHIvNep7CrLrtpLKf0sideiPhAP/PjtEejGAUvqL8yFzAhQb36Njq62XrjsCvuZYjZdcM9wpkONydfdE4jpFwu9R5Mu+kRej3AjpTjG5BYfPCrhD8gb+kyrIijzVaTFFGIsrgY92K65bbyMwQqqYlVXJ3ANNIZh09+ChlthjW+3ijYu70rnR5wBxLpCx/g4ZvBcDw9BxmGjkWfpWI2mhiZBGsn69Q56f8+pu2R/PtYiGXXu0gBbKavFF22y0MCtLjUYARfbeDHdSZOZTwosIAJj7XuPd3zsSSb7ZufwcZ8ohe2fa8q7HBHqabAV/++bICrM9exSXfzBEpIYkRnDJE0SLZrOndNLNKs7TUoTuM/AEBJvKMZgJIOcMGAhiWQBW+AUv71XNh+IcxKFOAjg1kNjcPhtuimipvSCiRkYqEMW3K+WUMgsj/o1ciYjF+cy1bpZd/f4/HXYi6jw7EU8UWwtyFmKAB1IQUNWVupvCQ9Xvcm7kc9jhH/Q+NraVoqvL0pH2cFtgXxA/3pPgfbRED9k17iuOJota+SX67iKFEKxhYh1wZIZ+hwQEK5cmuAHZGaC6ELPjU4qRzm19qN3+7mnUtaaYOQp4KiU9U2jisUKQHqA/4gjI/XvYttCQABMCrtoL2bUaMyQ3Ky9UfhgPTxlAJBL7EPcZ0awm2zshfQVEqnUHPL9R4sdUi5RxRJejGsbRa6ZphLj8QvJaBogpbPF4UtR8xJTAjBgkqhkiG9w0BCRUxFgQUJFcFXhXpJDan/9iGpWyxLWcUWPQwMTAhMAkGBSsOAwIaBQAEFHdXQzICVMicnErv3o77eCWzQocfBAivVb5Xu6Eh8gICCAA="));
keyStream.Seek(0, SeekOrigin.Begin);

var keyPassword = "1234";

var certStream = new MemoryStream();
await certStream.WriteAsync(Convert.FromBase64String(
    "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZTakNDQXpJQ0NRQ0tmS3NwV1g1ZmlEQU5CZ2txaGtpRzl3MEJBUXNGQURCbk1Rc3dDUVlEVlFRR0V3SkMKUlRFTE1Ba0dBMVVFQ0F3Q1FrVXhDekFKQmdOVkJBY01Ba0pGTVFzd0NRWURWUVFLREFKQ1JURUxNQWtHQTFVRQpDd3dDUWtVeEN6QUpCZ05WQkFNTUFrSkZNUmN3RlFZSktvWklodmNOQVFrQkZnaENSVUJDUlM1Q1JUQWVGdzB5Ck1EQTBNVGd3TVRVeE5UbGFGdzB5TVRBME1UZ3dNVFV4TlRsYU1HY3hDekFKQmdOVkJBWVRBa0pGTVFzd0NRWUQKVlFRSURBSkNSVEVMTUFrR0ExVUVCd3dDUWtVeEN6QUpCZ05WQkFvTUFrSkZNUXN3Q1FZRFZRUUxEQUpDUlRFTApNQWtHQTFVRUF3d0NRa1V4RnpBVkJna3Foa2lHOXcwQkNRRVdDRUpGUUVKRkxrSkZNSUlDSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF6VHFkaGdPWG9LY2JqUk80Q0FjRitMaUt2YTBjV2kveHZhKzYKeWFxcUR1TFB6bkQvWHZsUDYxZXBFMlF0K25xSWJobTBzcitXOGxsblBvWDB0UmdNOUc4Y1FxL1FWNWxMMDdJSAp4S1hUQ1FLNVV4MTNVVEN2ZC9hWFF5Mml0T1QyNldOY0dueUh4MU1QRFpGdTBVQ0NjSUV0ZE1PanBPVjI1dGtoClpleUlvVCtSUGp6cURHZzRpdlR6RDd4WFNqU21iR2Nmc29nZUEyNGNMM01qbWJRaGJPVnBnL0xjWVpxaUpURUIKQ0FHR0oxTTBFRk5BVEZ0S0NaQk8rQ1BEU2d2UFBFZXZxTkVSUTJ2S3Y0eHMxSk92VExreTU0VmU1cHhvQlhMTApJSlBKTzRMSWJTd0ZRUVV3d0F1OXBUUUpoWHE2Qi9ZZkNGVk1DK0lXNVVIYTBSaUlVUUZ2K3lzOC9SSFBycUNhCnMvQlE4TXdtbFkvZnRhQzVOK1hIMkZtdVVIbXFpZzg4bHFVRVhMeVk3YW4xcFhJaXJpN2w3UnBaUy91Yy8wUFUKVlRVcGR4cVNUMUl0OUJMT2FLZU0raXhDQnVFem9PbzJxYzRDSUE0d3ZGMU52WS9SZ3NUOS9GVFlSMUNwa1hONQpSeEk0Z293QkpYejZaY0o4QTNnVHBaSE9uUXY0Zjc5RDB5Y3RhSG9aTk5TZE1LVnBqbW1nVEI3UnBKMmlPL3BHCnRsTG1Ld2h5S2xnQ09aUndFZ0x4enJ5UzFkSzRUUncvSHB1enZWSlcyckE1ZG54UFZOSmxLem01U3NWdmNDcDQKbGRvQWc4dHNMMms5OEpHTkM3ZjlMZGFaZHhMZkx2L1dlVDNVV2FiV3B1eHpUa0xHVkx1WHl4UEZPZFBLN20xUgp4ZVJvUjRFQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBbkY1NGUzQm1WOUZHSGs2NnE4OFMybEZ0CjN1MUUxdGdMSkxqNnNmYmZ6NThPallGNGNOSDBsRUppcXJDUlQ2a1Y1MzlRdDNGOEIySlR3WFJGbjVIcmpFZTEKTGhueEJ1UG5oNTFnYkFmRTB6QisyUDlRU1JzbjYyVERlM0hwemRuTGhrV0dpY1BxVkJSMHZ3ZVZja1ZVZGs2NApDTk1ydDN0SFVXbFFBKzNaUCtNLzJZL3dUZTRKa1NkdEs3MWtwUWNkRWZsekNyeVBQREdzc1l0TzdCVHpSQVVWCjlIODFXbCtMTVhuNmlYYlNrT2JpajRtOG5ScFUzVjFFYi91bXFxTm1pNkdocm56SDhPY2R4Y2hrTWVkNmlDOU8KOS96S3l2ZURBNCs4TTQ4OXBENDNFVjVabFdkNDJ5RzlteCtNN1Z1UTUrNWpxejlMNUVIYWlvRGszMHN5dnkrUwp3eDV2WCswUHV0SytQRWpXUlZCS3F3OUozN2N0Vk4rYkpSeDZPRVZ6QkRIQ2gvbGFwZGNvakdjTFJXSE5hQjBxCmFQSWV5ODJFTUVETFYrMXNOcDlublViZ0FvYUtDOVJ4T3FPYzNsc3IwLzkvV1M2YjUwSUoyaE43RVhYOE14VGMKcmJqZTJ3MzhUa1ZDK05iZ0VUYUt2NzNmaTNTaE95UzlWaVZsMUFYWUowL1pBWitob2U3MFg2TEx3VmF3MDdNRQo5dFZjcVRUS01qanRyS0svMkJaWVBGT1E1NmxINk5yMUVRMXhQbjMwRDJMNVJVeGJhb1pSMUF5NlRTUlBIOURVCnZDc3BpUm9LcFRrZFU1WExrM2hUSDg2b1MwZjZyb2pwZDZ5b09FeDZrRXBvOSs4YUNNZitPR0wxVEZUMy9MclUKQnJJWXNrOVM1RVdPMkxCSWR0dz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="));
certStream.Seek(0, SeekOrigin.Begin);


var textPart = new TextPart("plain");
textPart.SetText(Encoding.ASCII, "Some text to sign");


MultipartSigned multipartSigned = new MultipartSigned();
using(var ctx = new TemporarySecureMimeContext())
using (var memory = new MemoryBlockStream())
{
    await textPart.WriteToAsync(memory);
    memory.Position = 0;
    
    var signer = new CmsSigner(keyStream, keyPassword)
    {
        DigestAlgorithm = DigestAlgorithm.Sha256
    };
    var signature = ctx.Sign(signer, memory);

    var micalg = ctx.GetDigestAlgorithmName(signer.DigestAlgorithm);
    multipartSigned.ContentType.Parameters["protocol"] = ctx.SignatureProtocol;
    multipartSigned.ContentType.Parameters["micalg"] = micalg;

    multipartSigned.Add(textPart);
    multipartSigned.Add(signature);
}

using (var ctx = new TemporarySecureMimeContext())
{
    var parser = new X509CertificateParser();
    var certs = parser.ReadCertificates(certStream);
    foreach (X509Certificate cert in certs)
    {
        ctx.Import(cert);
    }
    foreach (var signature in await multipartSigned.VerifyAsync (ctx)) {
        try
        {
            bool valid = signature.Verify();
        } catch (DigitalSignatureVerifyException e) {
            // There was an error verifying the signature.
            throw e;
        }
    }
}
```

**Comment by jstedfast** [comment] 2020-04-18 13:34
The problem is that there are no "trusted anchors". The TemporarySecureMimeContext considers self-signed certificates with the "CertSign" key usage flag to be "trusted anchors".

In your case, the TemporarySecureMimeContext only knows about 1 certificate which is a self-signed certificate but does not have the "CertSign" key usage capability.

If your plan is to use S/MIME like this, then I would recommend copying the source code for TemporarySecureMimeContext to your project and modifying it such that the `GetTrustedAnchors()` method adds all of your certificates to the HashSet that it returns instead of doing what it currently does.

I'm not sure that this is really a good idea for MimeKit itself to do though, so I'll have to close this as `wontfix`.

**Closed by jstedfast** 2020-04-18 13:34 UTC
Labels: question, wontfix
