### ISSUE TITLE
New MimeMessage throws exception: Could not load System.Text.Encoding.CodePages 4.1.1.0

### ISSUE THREAD

**Issue by LesGW** [jstedfast/MimeKit#827] opened 2022-08-11 14:55 UTC
I'm getting a {"The type initializer for 'MimeKit.ParserOptions' threw an exception."} exception on a new MimeMessage(); call.  The inner exceptions are:
{"The type initializer for 'MimeKit.Utils.CharsetUtils' threw an exception."}
and
{"Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}

**Platform (please complete the following information):**
 - OS: Windows 11
 - .NET Runtime: ??
 - .NET Framework: 4.6.2 - 
 - MimeKit Version: 3.3.0
 - System.Text.Encoding.CodePages: 6.0.0
 - 

**To Reproduce**
Just run the program in debug mode from VS 2019

**Expected behavior**
I would expect it to return me a MailMessage Object.

**Code Snippets**

```csharp
// Add your code snippet here.
var mymessage = new MimeMessage();

**Additional context**
Code was working a couple of days ago and suddenly started throwing this error.  There was a windows update today and  (I think) an update of the MimeKit depenncies.

**Comment by jstedfast** [comment] 2022-08-11 15:06
This is a duplicate of https://github.com/jstedfast/MimeKit/issues/816

**Closed by jstedfast** 2022-08-11 15:06 UTC
Labels: duplicate

**Comment by LesGW** [comment] 2022-08-11 15:20
OK. You closed it and said it’s a dup of 816 but how do I fix the problem?  Is there some coding I need to change?  I see lots of discussion in 816 but no indication of how to fix my code or whether there is an update of mimekit coming that will fix it.  Sorry but I’d like to be able to run my app again.

 

Les

**Comment by jstedfast** [comment] 2022-08-11 15:36
Read the last comment and try the latest build (not release).

Let me know if that solves the problem for you. If it does, I'll bump up the priority for making a new release.

**Comment by LesGW** [comment] 2022-08-11 16:18
3.3.0.517 solves the problem.  Thanks

Les
