### ISSUE TITLE
Unwanted carriage returns in result

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#206] opened 2015-12-10 20:00 UTC
Howdy,

When I create a message with one single entity of type text/plain, then send it to GMail using MailKit, for then to retrieve it again and parse it using MimeKit, the result is not what I started out with. There are two additional CR/LF appended into the result I am getting after parsing the message ...?

Not entirely sure if it is GMail messing up things, MailKit, or myself, but wanted to hear with you before I go too deep in if this is "known behaviour" or even expected ...?

The text I send is a single line of "Hello World" without any carriage returns what so ever, and it comes back with CR/LF+CR/LF appended after the text I sent ...

Slightly annoying ... :(

BTW, you will LOVE to see what I am creating from your baby ... :D

Everything MITx11 :D

**Comment by jstedfast** [comment] 2015-12-10 20:41
Well, it's expected that you'd at least have 1 added <CRLF>, but I don't know about 2.

You'll have to get a protocol log to see.

**Comment by jstedfast** [comment] 2015-12-14 02:15
FWIW, the parser doesn't add newlines, so the problem is that the input had the extra newlines. The question becomes: did it have extra newlines because MimeMessage.WriteTo() add them or did the SMTP or IMAP server add them?

Since the UnitTests.MimeMessageTests.TestReserialization() unit test shows no extra newlines added by MimeKit, I'm going to close this for now under the assumption that the problem is with the SMTP or IMAP server.

**Closed by jstedfast** 2015-12-14 02:15 UTC
