### ISSUE TITLE
System.Runtime.CompilerService.Unsafe dependency problem

### ISSUE THREAD

**Issue by jenswi** [jstedfast/MimeKit#1102] opened 2024-11-21 09:30 UTC
**Describe the bug**
MimeKit is dependent on System.Runtime.CompilerService.Unsafe 6.0.0 and System.Memory 4.5.5.
System.Memory 4.5.5 is dependent on System.Runtime.CompilerService.Unsafe 4.5.3.
This causes problems with dependencies, best thing would to downgrade MimeKit dependency for System.Runtime.CompilerService.Unsafe from 6.0.0 to 4.5.3 so MimeKit and MimeKits dependencies would be dependent on the same version of System.Runtime.CompilerService.Unsafe.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: .net 4.8
 - MimeKit Version: 4.7.1 and 4.8.0

**Comment by jstedfast** [comment] 2024-11-21 11:50
You are theorizing and you are wrong.

If you are experiencing the bug that I suspect you are, making the change you suggest won't fix it.

The problem is a bug in MSBuild and Microsoft has known about it for a while now.

The solution is to correctly configure your app.config with binding redirects.

**Closed** 2024-11-21 11:50 UTC

**Comment by jstedfast** [comment] 2024-12-10 00:46
MimeKit v4.9.0 now depends on System.Memory/System./Buffers which depend on System.Runtime.CompilerServices.Unsafe v6.1.0

This means that MimeKit no longer has an explicit dependency.

Maybe that will fix this for you.

**Comment by jenswi** [comment] 2024-12-10 04:54
After some testing got I got this working with exename.exe.config files, but it is always better to get it working with no workarounds.

Thank you.
