### ISSUE TITLE
NonRepudiation keyUsage can be used for signing

### ISSUE THREAD

**Issue by anaselhajjaji** [jstedfast/MimeKit#119] opened 2015-03-26 15:01 UTC
Actually, in CmsSigner class we have the following check:

if (flags != X509KeyUsageFlags.None && (flags & X509KeyUsageFlags.DigitalSignature) == 0)
throw new ArgumentException ("The certificate cannot be used for signing.");

Which is refuses NonRepudiation certificate keyUsage. Non repudiation key usage can be used for signature and the code must be changed to:
if ((flags != X509KeyUsageFlags.None && flags != X509KeyUsageFlags.NonRepudiation) && (flags & X509KeyUsageFlags.DigitalSignature) == 0)
throw new ArgumentException ("The certificate cannot be used for signing.");

**Comment by jstedfast** [comment] 2015-03-26 15:50
Thanks! This should be fixed now.

**Closed by jstedfast** 2015-03-26 15:50 UTC

**Comment by anaselhajjaji** [comment] 2015-03-27 10:11
Thanks for the correction. When do you plan to release a version containing this correction ?

**Comment by jstedfast** [comment] 2015-03-27 11:04
I'll probably release it this weekend. I prefer to collect as many bug fixes as I can before I release. The problem is I always seem to get the bug reports on the day after I make a release. :-(

**Comment by anaselhajjaji** [comment] 2015-03-27 11:23
OK thanks for your reactivity, we actually need the correction for our project.

**Comment by jstedfast** [comment] 2015-03-27 12:36
FWIW, I typically make a release every weekend for any week in which I've fixed at least 1 bug.
